CampusCRM\EventTopicsBundle\Entity\EventTopics:
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max:        255
            - CampusCRM\EventTopicsBundle\Validator\Constraints\UniqueName: { groups: [unique_name] }
