navigation:
    menu_config:
        templates:
            calendar_menu:
                template: 'OroCalendarBundle:Calendar:Menu/contextMenu.html.twig'
                root_class: 'dropdown-menu context-menu'
        items:
            marketing_tab:
                display: false
                display_children: false
            sales_tab:
                display: false
                display_children: false
            customers_tab:
                display: false
                display_children: false

            campus_contact_list:
                label: 'oro.contact.entity_plural_label'
                route: 'oro_contact_index'
                extras:
                    routes: ['/^oro_contact_(?!group\w+|group\w+)\w+$/']
                    description: 'oro.contact.menu.contact_list.description'
            campus_contact_group_list:
                label: 'oro.contact.group.entity_plural_label'
                route: 'oro_contact_group_index'
                extras:
                    routes:      ['oro_contact_group_*']
                    description: 'oro.contact.menu.contact_group_list.description'
            campus_contacts_tab:
                label: 'Contacts'
                uri: '#'
                extras:
                    position: 19
            campus_calendar_tab:
                label: 'Calendar'
                uri: '#'
                extras:
                    position: 20
            campus_calendar_event_list:
                label: 'oro.calendar.calendarevent.entity_plural_label'
                route: 'oro_calendar_event_index'
                extras:
                    position: 50
                    routes: ['oro_calendar_event_*']

        tree:
            application_menu:
                children:
                    campus_contacts_tab:
                        children:
                            campus_contact_list: ~
                            campus_contact_group_list: ~

                    campus_calendar_tab:
                        children:
                            oro_calendar_view_default: ~
                            campus_calendar_event_list: ~