services:
    campus_calendar.attendees_select.transformer:
        class: CampusCRM\CampusCalendarBundle\Form\DataTransformer\AttendeesToViewTransformer
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@campus_calendar.attendee_manager'

    campus_calendar.attendees_select.form.type:
        class: CampusCRM\CampusCalendarBundle\Form\Type\CalendarEventAttendeesSelectType
        arguments:
            - '@campus_calendar.attendees_select.transformer'
            - '@campus_calendar.attendee_manager'
            - '@campus_calendar.attendee_relation_manager'
        tags:
            - { name: form.type, alias: campus_calendar_event_attendees_select }

    campus_calendar.calendar_event.form.handler:
        class: CampusCRM\CampusCalendarBundle\Form\Handler\CalendarEventHandler
        parent: 'oro_calendar.calendar_event.form.handler.abstract'
        calls:
            - ['setForm', ['@oro_calendar.calendar_event.form']]
            - ['setEntityRoutingHelper', ['@oro_entity.routing_helper']]