parameters:
    campus_calendar.system_calendar.form.handler.class:           Oro\Bundle\CalendarBundle\Form\Handler\SystemCalendarHandler

services:
    campus_calendar.calendar_event.form.handler:
        class: 'CampusCRM\CampusCalendarBundle\Form\Handler\CalendarEventHandler'
        parent: 'oro_calendar.calendar_event.form.handler.abstract'
        calls:
            - ['setForm', ['@oro_calendar.calendar_event.form']]
            - ['setEntityRoutingHelper', ['@oro_entity.routing_helper']]