services:
    campus_calendar.calendar_event.form.extension.type:
            class: 'CampusCRM\CampusCalendarBundle\Form\Extension\CalendarEventTypeExtension'
            public: true
            arguments:
                - "@service_container"
            tags:
                - { name: form.type_extension, alias: oro_calendar_event }

    campus_calendar.calendar_event.api.form.extension.type:
            class: 'CampusCRM\CampusCalendarBundle\Form\Extension\CalendarEventApiTypeExtension'
            public: true
            arguments:
                - "@service_container"
            tags:
                - { name: form.type_extension, alias: oro_calendar_event_api }