services:
    campus_calendar.attendees_select.transformer:
        class: CampusCRM\CampusCalendarBundle\Form\DataTransformer\AttendeesToViewTransformer
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@campus_calendar.attendee_manager'

    campus_calendar.attendees_api.form.type:
        class: CampusCRM\CampusCalendarBundle\Form\Type\CalendarEventAttendeesApiType
        tags:
            - { name: form.type, alias: campus_calendar_event_attendees_api }

    campus_calendar.attendees_select.form.type:
        class: CampusCRM\CampusCalendarBundle\Form\Type\CalendarEventAttendeesSelectType
        arguments:
            - '@campus_calendar.attendees_select.transformer'
            - '@campus_calendar.attendee_manager'
            - '@campus_calendar.attendee_relation_manager'
        tags:
            - { name: form.type, alias: campus_calendar_event_attendees_select }

    campus_calendar.calendar_event.form.handler:
        class: CampusCRM\CampusCalendarBundle\Form\Handler\CalendarEventHandler
        parent: 'oro_calendar.calendar_event.form.handler.abstract'
        calls:
            - ['setForm', ['@oro_calendar.calendar_event.form']]
            - ['setEntityRoutingHelper', ['@oro_entity.routing_helper']]

    campus_calendar.calendar_event.form.extension.type:
        class: 'CampusCRM\CampusCalendarBundle\Form\Extension\CalendarEventTypeExtension'
        public: true
        arguments:
            - "@service_container"
        tags:
            - { name: form.type_extension, alias: oro_calendar_event }

    #oro_calendar.calendar_event.form.api:
    #    class:   'Symfony\Component\Form\Form'
    #    factory: 'form.factory:createNamed'
    #    arguments:
    #        - ~
    #        - "oro_calendar_event_api"

    #oro_calendar.calendar_event.form.type.api:
    #    class: '%oro_calendar.calendar_event.form.type.api.class%'
    #    arguments:
    #        - '@oro_calendar.calendar_event_manager'
    #        - '@oro_calendar.calendar_event.notification_manager'
    #    tags:
    #        - { name: form.type, alias: oro_calendar_event_api }

    campus_calendar.calendar_event.api.form.extension.type:
        class: 'CampusCRM\CampusCalendarBundle\Form\Extension\CalendarEventApiTypeExtension'
        public: true
        arguments:
            - "@service_container"
        tags:
            - { name: form.type_extension, alias: oro_calendar_event_api }