services:
      campus_calendar.listener.calendar_event_attendees:
        class: CampusCRM\CampusCalendarBundle\EventListener\CalendarEventAttendeesListener
        arguments:
            - '@service_container'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

      attendance.twig_extension:
        class: CampusCRM\CampusCalendarBundle\Twig\AttendanceExtension
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }

      academic_calendar:
        class:  CampusCRM\CampusCalendarBundle\Provider\AcademicCalendar
        arguments:
                  - '@doctrine.orm.entity_manager'

      frequency_manager:
        class:  CampusCRM\CampusCalendarBundle\Manager\FrequencyManager
        arguments:
                  - '@doctrine.orm.entity_manager'

      campus_calendar.autocomplete.attendee_search_handler:
        class: CampusCRM\CampusCalendarBundle\Autocomplete\AttendeeSearchHandler
        parent: oro_activity.form.handler.autocomplete
        calls:
                  - [setAttendeeManager, ['@campus_calendar.attendee_manager']]

      campus_calendar.attendee_manager:
        class: CampusCRM\CampusCalendarBundle\Manager\AttendeeManager
        arguments:
                  - '@oro_entity.doctrine_helper'
                  - '@campus_calendar.attendee_relation_manager'

      campus_calendar.attendee_relation_manager:
        class: CampusCRM\CampusCalendarBundle\Manager\AttendeeRelationManager
        arguments:
                  - '@doctrine'
                  - '@oro_locale.formatter.name'
                  - '@oro_locale.dql.formatter.name'

      campus_calendar.calendar_event.update_attendee_manager:
        class: 'CampusCRM\CampusCalendarBundle\Manager\CalendarEvent\UpdateAttendeeManager'
        public: false
        arguments:
            - '@campus_calendar.attendee_relation_manager'
            - '@doctrine'

      campus_calendar.calendar_event.update_manager:
        class: 'CampusCRM\CampusCalendarBundle\Manager\CalendarEvent\UpdateManager'
        public: false
        arguments:
            - '@campus_calendar.calendar_event.update_attendee_manager'
            - '@oro_calendar.calendar_event.update_child_manager'
            - '@oro_calendar.calendar_event.update_exception_manager'

      oro_calendar.calendar_event_manager:
        class: CampusCRM\CampusCalendarBundle\Manager\CalendarEventManager
        arguments:
            - '@campus_calendar.calendar_event.update_manager'
            - '@doctrine'
            - '@oro_security.security_facade'
            - '@oro_entity.entity_name_resolver'
            - '@oro_calendar.system_calendar_config'
