services:
    campus_calendar.attendees_select.form.extension.type:
        class: 'CampusCRM\CampusCalendarBundle\Form\Extension\CalendarEventAttendeesSelectTypeExtension'
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type_extension, alias: oro_calendar_event_attendees_select }

    campus_calendar.calendar_event.form.handler:
        class: CampusCRM\CampusCalendarBundle\Form\Handler\CalendarEventHandler
        parent: 'oro_calendar.calendar_event.form.handler.abstract'
        calls:
            - ['setForm', ['@oro_calendar.calendar_event.form']]
            - ['setEntityRoutingHelper', ['@oro_entity.routing_helper']]
            - ['setAttendeeRelationManager', ['@oro_calendar.attendee_relation_manager']]

    campus_calendar.calendar_event.form.handler.api:
        class: 'CampusCRM\CampusCalendarBundle\Form\Handler\CalendarEventApiHandler'
        parent: 'oro_calendar.calendar_event.form.handler.abstract'
        calls:
            - ['setForm', ['@oro_calendar.calendar_event.form.api']]
            - ['setAttendeeRelationManager', ['@oro_calendar.attendee_relation_manager']]

    campus_calendar.calendar_event.form.extension.type:
        class: 'CampusCRM\CampusCalendarBundle\Form\Extension\CalendarEventTypeExtension'
        public: true
        autowire: true
        arguments:
            - "@service_container"
        tags:
            - { name: form.type_extension, alias: oro_calendar_event }

    campus_calendar.calendar_event.api.form.extension.type:
        class: 'CampusCRM\CampusCalendarBundle\Form\Extension\CalendarEventApiTypeExtension'
        public: true
        arguments:
            - "@service_container"
        tags:
            - { name: form.type_extension, alias: oro_calendar_event_api }