services:
      campus_calendar.listener.calendar_event_attendees:
        class: CampusCRM\CampusCalendarBundle\EventListener\CalendarEventAttendeesListener
        arguments:
            - '@service_container'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

      attendance.twig_extension:
        class: CampusCRM\CampusCalendarBundle\Twig\AttendanceExtension
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }

      academic_calendar:
        class:  CampusCRM\CampusCalendarBundle\Manager\AcademicCalendarManager
        arguments:
                  - '@doctrine.orm.entity_manager'

      frequency_manager:
        class:  CampusCRM\CampusCalendarBundle\Manager\FrequencyManager
        arguments:
                  - '@doctrine.orm.entity_manager'