services:
    campus_activity.form.handler.autocomplete:
        class: CampusCRM\CampusActivityBundle\Autocomplete\ContextSearchHandler
        arguments:
            - '@security.token_storage'
            - '@translator'
            - '@oro_search.index'
            - '@oro_activity.manager'
            - '@oro_entity_config.config_manager'
            - '@oro_entity.entity_class_name_helper'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity.entity_name_resolver'
            - '@event_dispatcher'