workflows:
    contact_followup:
        entity: Oro\Bundle\ContactBundle\Entity\Contact
        entity_attribute: contact
        force_autostart: false
        steps_display_ordered: true
        defaults:
            active: true
        priority: 100
        applications: [ 'default' ]
        start_step: unassigned
        steps:
            unassigned:
                order: 10
                allowed_transitions:
                    - assign
                    - close
            assigned:
                order: 20
                allowed_transition:
                    - followup
            followup:
                order: 30
                allowed_transitions:
                    - open
                    - close
            open:
                order: 40
                allowed_transitions:
                    - close
            close:
                order: 50
                allowed_transitions:
                    - reopen
        attributes:
            assigned_to:
                type: entity
                options:
                    class: Oro\Bundle\UserBundle\Entity\User
            owner:
                type: entity
                options:
                    class: Oro\Bundle\UserBundle\Entity\User
            contact_status:
                type: object
                property_path: contact.contactStatus
              #  options:
              #      class: Oro\Bundle\ContactBundle\Entity\Contact
        transitions:
            assign:
                step_to:  assigned
                is_start: true
                is_unavailable_hidden: true
             #   acl_resource: oro_sales_opportunity_create
                frontend_options:
                    icon: 'fa-usd'
                transition_definition: assign_definition
                form_options:
                    attribute_fields:
                        assigned_to:
                            form_type: oro_user_select
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        owner:
                            form_type: oro_user_select
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
            reopen:
                step_to: followup
                transition_definition: def
            follow_up:
                is_start: true
                step_to: followup
                transition_definition: def
                #frontend_options:
                 #   icon: bar
            open:
                step_to: open
                transition_definition: def
                #frontend_options:
                 #   icon: bar
            close:
                step_to: close
                transition_definition: def
                #frontend_options:
                 #   icon: bar
                form_options:                               # options which will be passed to form type of transition
                    attribute_fields:                       # list of attribute fields which will be shown
                        contact_status:                       # attribute name
                            options:                        # list of form field options
                                form_type: enum
                                required: true              # define this field as required
                                constraints:                # list of constraints
                                    - NotBlank: ~           # this field must be filled
        transition_definitions:
             def: ~