datagrids:

    # contacts main grid show on oro_contact_index route
    all-contacts-grid:
        extends: contacts-grid
        columns:
            firstName:
                label:         oro.contact.first_name.label
            lastName:
                label:         oro.contact.last_name.label
            birthday:
                label:         oro.contact.birthday.label
                frontend_type: date
                renderable: false
            gender:
                label:         oro.contact.gender.label
                frontend_type: select
                choices: "@oro_user.gender_provider->getChoices"
                renderable: false
            email:
                label:         oro.contact.email.label
                inline_editing:
                    enable: true
                    validation_rules:
                        Email: true
                    save_api_accessor:
                        class: orocontact/js/datagrid/inline-editing/save-api-accessor
                        route_create_entity:
                            name: oro_api_post_contact_email
                            http_method: POST
                        route_delete_entity:
                            name: oro_api_delete_contact_email
                            http_method: DELETE
                        default_route_parameters:
                            className: Oro_Bundle_ContactBundle_Entity_ContactEmail
                        route_parameters_rename_map:
                            emailId: id
            phone:
                label:         oro.contact.contactphone.phone.label
                frontend_type: phone
                inline_editing:
                    enable: true
                    editor:
                        view: oroform/js/app/views/editor/text-editor-view
                    save_api_accessor:
                        class: orocontact/js/datagrid/inline-editing/save-api-accessor
                        route_create_entity:
                            name: oro_api_post_contact_phone
                            http_method: POST
                        route_delete_entity:
                            name: oro_api_delete_contact_phone
                            http_method: DELETE
                        default_route_parameters:
                            className: Oro_Bundle_ContactBundle_Entity_ContactPhone
                        route_parameters_rename_map:
                            phoneId: id
            fax:
                label:         oro.contact.fax.label
                frontend_type: phone
                renderable:    false
            skype:
                label:         oro.contact.skype.label
                frontend_type: string
                renderable:    false
            twitter:
                label:         oro.contact.twitter.label
                frontend_type: string
                renderable:    false
            facebook:
                label:         oro.contact.facebook.label
                frontend_type: string
                renderable:    false
            linkedIn:
                label:         oro.contact.linked_in.label
                frontend_type: string
                renderable:    false
            googlePlus:
                label:         oro.contact.google_plus.label
                frontend_type: string
                renderable:    false
            source:
                label:         oro.contact.source.label
                renderable:    false
            countryName:
                label:         oro.contact.contactaddress.country.label
                renderable:    false
            regionLabel:
                label:         oro.contact.contactaddress.region.label
                renderable:    false
            addressPostalCode:
                label:         oro.contact.contactaddress.postal_code.label
                renderable:    false
            addressCity:
                label:         oro.contact.contactaddress.city.label
                renderable:    false
            addressStreet:
                label:         oro.contact.contactaddress.street.label
                renderable:    false
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
                renderable:    false
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
                renderable:    false
            pictureFilename:
                label:         oro.contact.picture.label
                renderable:    false
            ownerName:
                label:         oro.contact.owner.label
                renderable: false
            assignedName:
                label:         oro.contact.assigned_to.label
                renderable: false
            reportsName:
                label:         oro.contact.reports_to.label
                renderable: false