workflows:
    contact_followup:
        entity: Oro\Bundle\ContactBundle\Entity\Contact
        entity_attribute: contact
        force_autostart: false
        steps_display_ordered: true
        defaults:
            active: true
        priority: 100
        applications: [ 'default' ]
        start_step: unassigned
        steps:
            unassigned:
                order: 10
                allowed_transitions:
                    - assign
                    - close
            assigned:
                order: 20
                allowed_transitions:
                    - followup
            followup:
                order: 30
                allowed_transitions:
                    - open
                    - close
            open:
                order: 40
                allowed_transitions:
                    - close
            closed:
                order: 50
                allowed_transitions:
                    - reopen
        attributes:
            assigned_to:
                type: entity
                options:
                    class: Oro\Bundle\UserBundle\Entity\User
            owner:
                type: entity
                options:
                    class: Oro\Bundle\UserBundle\Entity\User
            auto_allocate:
                type: boolean
                property_path: contact.auto_allocate
            #contact_status:
            ##    type: array
             #   property_path: contact.contactStatus
              #  options:
              #      class: Oro\Bundle\ContactBundle\Entity\Contact
        transitions:
            assign:
                step_to:  assigned
#                is_start: true
                is_unavailable_hidden: true
             #   acl_resource: oro_sales_opportunity_create
                frontend_options:
                    icon: 'fa-usd'
                transition_definition: assign_def
                form_options:
                    attribute_fields:
                        assigned_to:
                            form_type: oro_user_select
                            options:
                                required: false
                        owner:
                            form_type: oro_user_select
                            options:
                                required: false
                        auto_allocate:
                            form_type: checkbox
                            options:
                                required: true
                    attribute_default_values:
                        owner: $contact.owner
                        auto_allocate: true
            reopen:
                step_to: followup
                transition_definition: reopen_def
            followup:
                step_to: followup
                transition_definition: followup_def
                #frontend_options:
                 #   icon: bar
            open:
                step_to: open
                transition_definition: open_def
                #frontend_options:
                 #   icon: bar
            close:
                step_to: closed
                transition_definition: close_def
                #frontend_options:
                 #   icon: bar
               # form_options:                               # options which will be passed to form type of transition
               #     attribute_fields:                       # list of attribute fields which will be shown
               ##         contact_status:                       # attribute name
                #            options:                        # list of form field options
               #                 form_type: enum
               ##                 required: true              # define this field as required
                ##                constraints:                # list of constraints
                  #                  - NotBlank: ~           # this field must be filled
        transition_definitions:
             assign_def:
                # Either auto allocate have value or assigned have value.
                # Both cannot have value. One have to be null.
                conditions:
                # ($assignedTo not empty AND $auto_allocate is false) OR
                # ($assignedTo is empty AND $auto_allocate is true)
                  '@or':
                      - '@and':
                          message: You must select either Assigned to or Auto allocate. But you cannot select both.
                          parameters:
                            - '@not_empty': [$assigned_to]
                            - '@equal': [$auto_allocate,false]
                      - '@and':
                          parameters:
                            - '@empty': [$assigned_to]
                            - '@equal': [$auto_allocate,true]
                actions:
                  - '@auto_allocate_workflow':
                      assigned_to: $assigned_to
                      owner: $owner
                      entity_class: $.entity
                      auto_allocate: $auto_allocate
             reopen_def: ~
             followup_def: ~
             open_def: ~
             close_def: ~