datagrids:
    campus_calendar-event-grid:
        acl_resource: oro_calendar_event_view
        source:
            type: orm
            query:
                select:
                    - partial event.{ id, start, recurrence, cancelled }
                    - a.displayName
                    - event.id
                    - COALESCE(calendar.name, CONCAT_WS(' ', owner.firstName, owner.lastName)) AS name
                    - event.title
                    - event.start
                    - event.end
                    - COALESCE(status.id, 'Oro\Bundle\CalendarBundle\Entity\Attendee::STATUS_NONE') as invitationStatus
                    - parent.id as parentId
                    - owner.id as ownerId
                    - relatedAttendeeUser.id as relatedAttendeeUserId
                    - (CASE WHEN (event.recurrence IS NOT NULL OR parent.recurrence IS NOT NULL) THEN true ELSE false END) as is_recurrent
                    - recurringEvent
                    - recurringEventRecurrence
                    - parent
                    - parentRecurringEvent
                    - parentRecurringEventRecurrence
                from:
                    - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
                join:
                    left:
                        - { join: event.parent, alias: parent }
                        - { join: event.relatedAttendee, alias: ra }
                        - { join: event.attendees, alias: a }
                        - { join: ra.status, alias: status }
                        - { join: ra.user, alias: relatedAttendeeUser }
                        - { join: event.recurrence, alias: recurrence }
                        - { join: event.recurringEvent, alias: recurringEvent }
                        - { join: recurringEvent.recurrence, alias: recurringEventRecurrence }
                        - { join: parent.recurringEvent, alias: parentRecurringEvent }
                        - { join: parentRecurringEvent.recurrence, alias: parentRecurringEventRecurrence }
                    inner:
                        - { join: event.calendar, alias: calendar }
                        - { join: calendar.owner, alias: owner }
                        -
                            join: %oro_calendar.calendar_property.entity.class%
                            alias: connection
                            conditionType: WITH
                            condition: "connection.calendarAlias = 'user' AND connection.calendar = calendar.id AND connection.visible = true"
                        - { join: connection.targetCalendar, alias: targetCalendar }
                where:
                    and:
                        - targetCalendar.owner = @oro_security.security_facade->getLoggedUserId
                        - event.cancelled = false
                        - event.id = :eventId
                groupBy: >
                    event.id,
                    calendar.name,
                    owner.firstName,
                    owner.lastName,
                    parent.id,
                    owner.id,
                    status.id,
                    relatedAttendeeUser.id,
                    recurrence.id,
                    recurringEvent.id,
                    recurringEventRecurrence.id,
                    parentRecurringEvent.id,
                    parentRecurringEventRecurrence.id
            bind_parameters:
                eventId: viewEventId
        columns:
            displayName:
                label: oro.calendar.calendarevent.title.label
            title:
                label: oro.calendar.calendarevent.title.label
            name:
                label: oro.calendar.calendarevent.calendar.label
            start:
                label: oro.calendar.calendarevent.start.label
                frontend_type: datetime
            end:
                label: oro.calendar.calendarevent.end.label
                frontend_type: datetime
            is_recurrent:
                label: oro.calendar.calendarevent.recurrence.alias.recurrent
                frontend_type: boolean
            recurrence:
                label: oro.calendar.calendarevent.recurrence.label
                type: twig
                template: OroCalendarBundle:CalendarEvent:Datagrid/Property/recurrence.html.twig
                frontend_type: html
            invitationStatus:
                label: oro.calendar.calendarevent.invitation_status.label
                type: twig
                template: OroCalendarBundle:CalendarEvent:Datagrid/Property/status.html.twig
                frontend_type: html
        sorters:
            columns:
                title:
                    data_name: event.title
                name:
                    data_name: name
                start:
                    data_name: event.start
                end:
                    data_name: event.end
                invitationStatus:
                    data_name: invitationStatus
            default:
                start: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: event.title
                name:
                    type: string
                    data_name: name
                start:
                    type: datetime
                    data_name: event.start
                end:
                    type: datetime
                    data_name: event.end
                is_recurrent:
                    type: boolean
                    data_name: is_recurrent
                invitationStatus:
                    type: enum
                    enum_code: ce_attendee_status
                    data_name: invitationStatus
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_calendar_event_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_calendar_event_update
                params:     [ id ]
            delete_link:
                type:     callback
                callable: "@oro_calendar.datagrid.helper.calendar_event_grid->getDeleteLinkProperty"
                route:    oro_calendar_event_delete
            accept_link:
                type:       url
                route:      oro_calendar_event_accepted
                params:     [ id ]
            tentative_link:
                type:       url
                route:      oro_calendar_event_tentative
                params:     [ id ]
            decline_link:
                type:       url
                route:      oro_calendar_event_declined
                params:     [ id ]
        actions:
            accept:
                type:         ajax
                label:        oro.calendar.calendarevent.action.status.accepted.label
                link:         accept_link
                icon:         check
                acl_resource: oro_calendar_event_view
            tentative:
                type:         ajax
                label:        oro.calendar.calendarevent.action.status.tentative.label
                link:         tentative_link
                icon:         question
                acl_resource: oro_calendar_event_view
            decline:
                type:         ajax
                label:        oro.calendar.calendarevent.action.status.declined.label
                link:         decline_link
                icon:         close
                acl_resource: oro_calendar_event_view
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye
                acl_resource: oro_calendar_event_view
                rowAction:    true
            update:
                type:          navigate
                acl_resource:  oro_calendar_event_create
                label:         oro.grid.action.update
                icon:          pencil-square-o
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_calendar_event_delete
                label:         oro.grid.action.delete
                icon:          trash-o
                link:          delete_link
        action_configuration: ['@oro_calendar.datagrid.action_permission_provider', "getInvitationPermissions"]
        mass_actions:
            delete:
                type: delete
                icon: trash
                label: oro.grid.action.delete
                entity_name: Oro\Bundle\CalendarBundle\Entity\CalendarEvent
                data_identifier: event.id
                handler: oro_calendar.datagrid.mass_action.handler.delete
        options:
            entityHint: calendar event
            entity_pagination: true

    campuscalendar-event-attendance-grid:
        acl_resource: oro_calendar_event_view
        source:
            type: orm
            query:
                select:
                      - a.id as id
                      - a.displayName as Name
                      - a.email
                from:
                      - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
                where:
                    and:
                      - event.id = :eventId
                join:
                    inner:
                      - { join: event.attendees, alias: a }
            bind_parameters:
                eventId: viewEventId
        columns:
            id:
                label: 'id'
            Name:
                label: 'Name'
            Email:
                lable: 'Email'
        sorters:
            columns:
                Name:
                    data_name: Name

    campuscalendar-event-grid:
        acl_resource: oro_calendar_event_view
        source:
            type: orm
            query:
                select:
                      - lead.id
                      - CONCAT(lead.firstName, ' ', lead.lastName) as Name
                from:
                      - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
                where:
                    and:
                      - event.id = :eventId
                join:
                    inner:
                      - { join: event.lead_23c40e3e, alias: lead }
            bind_parameters:
                eventId: viewEventId
        columns:
            Name:
                label: 'Name'
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_sales_lead_view
                params:     [ id ]
        sorters:
            columns:
                Name:
                    data_name: Name
        actions:
            view:
                type:          navigate
                acl_resource:  oro_sales_lead_view
                label:         oro.grid.action.view
                icon:          eye
                link:          view_link
                rowAction:     true
        filters:
            columns:
                name:
                    type: string
                    data_name: Name

    attendance-contacts-grid:
        acl_resource: oro_contact_view
        source:
            type: orm
            query:
                select:
                    - c.id
                    - CONCAT_WS(' ', c.firstName, c.lastName) as Name
                    - email.email as Email
                    - >
                      (
                        CASE WHEN c.id IN c.id
                        THEN true ELSE false END
                      ) as Attendance
                from:
                    - { table: %oro_contact.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.emails, alias: email, conditionType: WITH, condition: 'email.primary = true' }
            bind_parameters:
                    - event_id
        columns:
            Attendance:
                label: 'Attendance'
                editable: true
                frontend_type: boolean
            Name:
                label: 'Name'
            Email:
                label: 'Email'
        properties:
            id: ~
        sorters:
            columns:
                Attendance:
                    data_name: Attendance
                Name:
                    data_name: Name

    campuscontact-group-contacts-grid:
        acl_resource: oro_contact_view
        source:
            type: orm
            query:
                select:
                    - c.id
                    - c.firstName
                    - c.lastName
                    - >
                        CASE WHEN (c.id IN (:attendees) OR c.id IN (:data_in)) AND c.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                        as hasGroup
                from:
                    - { table: %oro_contact.entity.class%, alias: c }
            bind_parameters:
                - attendees
        columns:
            hasGroup:
                label: oro.contact.group.has_group.label
                editable: true
                frontend_type: boolean
            id:
                label: 'id'
            firstName:
                label: oro.contact.first_name.label
            lastName:
                label: oro.contact.last_name.label
        properties:
            id: ~
        filters:
            columns:
                hasGroup:
                    data_name: hasGroup
                    type:  boolean
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.firstName
        sorters:
            columns:
                hasGroup:
                    data_name: hasGroup
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
            default: { hasGroup: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        options:
            entityHint: contacts
            rowSelection:
                dataField: id
                columnName: hasGroup
                selectors:
                    included: '#groupAppendContacts'
                    excluded: '#groupRemoveContacts'

    campuscontacts-select-grid:
        extended_entity_name: %oro_contact.entity.class%
        acl_resource: oro_contact_view
        source:
            type: orm
            query:
                select:
                    - c.id
                    - c.firstName
                    - c.lastName
                    - contactSource.label as contactSourceLabel
                    - email.email as primaryEmail
                    - phone.phone as primaryPhone
                    - CONCAT(CASE WHEN address.regionText IS NOT NULL THEN address.regionText ELSE region.name END, '') as regionLabel
                    - country.name as countryName
                    - address.postalCode as addressPostalCode
                from:
                    - { table: %oro_contact.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.addresses, alias: address, conditionType: WITH, condition: 'address.primary = true' }
                        - { join: c.emails, alias: email, conditionType: WITH, condition: 'email.primary = true' }
                        - { join: c.phones, alias: phone, conditionType: WITH, condition: 'phone.primary = true' }
                        - { join: c.source, alias: contactSource }
                        - { join: address.country, alias: country }
                        - { join: address.region, alias: region }
            bind_parameters:
                - group
            hints:
                - HINT_TRANSLATABLE
        columns:
            firstName:
                label: oro.contact.first_name.label
            lastName:
                label: oro.contact.last_name.label
            primaryEmail:
                label: oro.contact.email.label
            primaryPhone:
                label: oro.contact.contactphone.phone.label
                frontend_type: phone
            contactSourceLabel:
                label: oro.contact.source.label
            countryName:
                label: oro.contact.contactaddress.country.label
            regionLabel:
                label: oro.contact.contactaddress.region.label
            addressPostalCode:
                label: oro.contact.contactaddress.postal_code.label
        sorters:
            columns:
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
                primaryEmail:
                    data_name: email.email
                primaryPhone:
                    data_name: phone.phone
                contactSourceLabel:
                    data_name: contactSource.label
                countryName:
                    data_name: country.name
                regionLabel:
                    data_name: regionLabel
                addressPostalCode:
                    data_name: address.postalCode
            default:
                lastName:  %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
                firstName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName
                primaryEmail:
                    type: string
                    data_name: email.email
                primaryPhone:
                    type: string
                    data_name: phone.phone
                contactSourceLabel:
                    type: entity
                    data_name: contactSource.name
                    enabled: false
                    options:
                        field_options:
                            class: OroContactBundle:Source
                            property: label
                            translatable_options: false
                countryName:
                    type: entity
                    data_name: address.country
                    enabled: false
                    options:
                        field_options:
                            class: OroAddressBundle:Country
                            property: name
                            query_builder: "@oro_contact.contact.datagrid_helper->getCountryFilterQueryBuilder"
                            translatable_options: false
                regionLabel:
                    type: string
                    data_name: regionLabel
                    enabled: false
                addressPostalCode:
                    type: string
                    data_name: addressPostalCode
                    enabled: false
        properties:
            id: ~
        options:
            entityHint: contacts