navigation:
    menu_config:
        templates:
            calendar_menu:
                template: 'OroCalendarBundle:Calendar:Menu/contextMenu.html.twig'
                root_class: 'dropdown-menu context-menu'
        items:
            marketing_tab:
                display: false
                display_children: false
            sales_tab:
                display: false
                display_children: false
            customers_tab:
                display: false
                display_children: false

            campus_contact_list:
                label: 'oro.contact.entity_plural_label'
                route: 'oro_contact_index'
                position: 10
                extras:
                    routes: ['/^oro_contact_(?!group\w+|group\w+)\w+$/']
                    description: 'oro.contact.menu.contact_list.description'

            contact_group_list:
                label: 'oro.contact.group.entity_plural_label'
                route: 'oro_contact_group_index'
                position: 30
                extras:
                    routes:      ['oro_contact_group_*']
                    description: 'oro.contact.menu.contact_group_list.description'

            campus_contacts_tab:
                label: 'Contacts'
                uri: '#'
                extras:
                    position: 19

            campus_calendar_tab:
                label: 'Calendar'
                uri: '#'
                extras:
                    position: 20

            oro_calendar_view_default:
                label: 'oro.calendar.menu.view_default'
                route: 'oro_calendar_view_default'
                extras:
                    position: 20
            oro_calendar_remove_action:
                label: 'oro.calendar.context.remove'
                uri: '#'
                extras:
                    position: 20
                    module: 'orocalendar/js/calendar/menu/remove-calendar'
                    template: 'OroCalendarBundle:Calendar:Menu/removeCalendar.html.twig'
            oro_calendar_toggle_action:
                uri: '#'
                extras:
                    position: 10
                    module: 'orocalendar/js/calendar/menu/toggle-calendar'
                    template: 'OroCalendarBundle:Calendar:Menu/toggleCalendar.html.twig'
            oro_calendar_menu_divider:
                label: ''
                extras:
                    divider: true
                    position: 95
            oro_calendar_color_action:
                uri: '#'
                extras:
                    position: 100
                    module: 'orocalendar/js/calendar/menu/change-calendar-color'
                    template: 'OroCalendarBundle:Calendar:Menu/changeCalendarColor.html.twig'
            calendar_event_list:
                display: false
                display_children: false
            campus_calendar_event_list:
                label: 'oro.calendar.calendarevent.entity_plural_label'
                route: 'oro_calendar_event_index'
                extras:
                    position: 50
                    routes: ['oro_calendar_event_*']
            oro_system_calendar_list:
                label: 'oro.calendar.systemcalendar.entity_plural_label'
                route: 'oro_system_calendar_index'
                extras:
                    position: 95
                    routes: ['oro_system_calendar_*']

        tree:
            application_menu:
                children:
                    campus_contacts_tab:
                        children:
                            campus_contact_list: ~
                            contact_group_list: ~

                    campus_calendar_tab:
                        children:
                            oro_calendar_view_default: ~
                            campus_calendar_event_list: ~
            usermenu:
                children:
                    oro_calendar_view_default: ~

            calendar_menu:
                type: calendar_menu
                children:
                    oro_calendar_remove_action: ~
                    oro_calendar_toggle_action: ~
                    oro_calendar_menu_divider: ~
                    oro_calendar_color_action: ~

    titles:
        oro_calendar_view_default: "My Calendar - %%username%%"
        oro_calendar_view: "%%calendarname%% - Calendars - %%username%%"
        oro_calendar_event_index: ~
        oro_calendar_event_view: '%%entity.title%%'
        oro_calendar_event_create: oro.ui.create_entity
        oro_calendar_event_update: '%%entity.title%% - Edit'
        oro_system_calendar_index:  ~
        oro_system_calendar_view: '%%entity.title%%'
        oro_system_calendar_create: oro.ui.create_entity
        oro_system_calendar_update: '%%entity.title%% - Edit'
        oro_system_calendar_event_view: '%%entity.title%% - %%parent.name%%'
        oro_system_calendar_event_create: 'oro.ui.create_entity - %%parent.name%%'
        oro_system_calendar_event_update: '%%entity.title%% - Edit - %%parent.name%%'

    navigation_elements:
        pinButton:
            routes:
                oro_calendar_view:         false
                oro_calendar_view_default: false
        favoriteButton:
            routes:
                oro_calendar_view:         false
                oro_calendar_view_default: false
