# src/CampusCRM/CampusCalendarBundle/Resources/config/oro/routing.yml
campuscrm_parent_bundle:
    resource:     "@!OroCalendarBundle/Controller"
    type:         annotation
    prefix:       /calendar