# src/CampusCRM/CampusCalendarBundle/Resources/config/oro/routing.yml
campuscrm_parent_bundle:
    resource:     "@!OroCalendarBundle/Controller"
    type:         annotation
    prefix:       /calendar

oro_sytem_calendar:
    resource:     "@!OroCalendarBundle/Controller/SystemCalendarController.php"
    type:         annotation
    prefix:       /system-calendar

oro_sytem_calendar_event:
    resource:     "@!OroCalendarBundle/Controller/SystemCalendarEventController.php"
    type:         annotation
    prefix:       /system-calendar