datagrids:
# contacts main grid show on oro_contact_index route
    campus-contacts-grid:
        extended_entity_name: %oro_contact.entity.class%
        mixins:
            - activity-contact-data-hidden-mixin
            - activity-contact-days-since-last-contact-hidden-mixin
        acl_resource: oro_contact_view
        source:
            type: orm
            query:
                select:
                    - c.id
                    - c.firstName
                    - c.lastName
                    - c.createdAt
                    - c.updatedAt
                    - c.birthday
                    - c.gender
                    - email.email
                    - email.id as emailId
                    - phone.phone
                    - phone.id as phoneId
                    - CONCAT(CASE WHEN address.regionText IS NOT NULL THEN address.regionText ELSE region.name END, '') as regionLabel
                    - country.name as countryName
                    - address.postalCode as addressPostalCode
                    - address.city as addressCity
                    - address.street as addressStreet
                    - CONCAT_WS(' ', c.firstName, c.lastName) as fullName
                    - CONCAT_WS(' ', o.firstName, o.lastName) as ownerName
                from:
                    - { table: %oro_contact.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.addresses, alias: address, conditionType: WITH, condition: 'address.primary = true' }
                        - { join: c.emails, alias: email, conditionType: WITH, condition: 'email.primary = true' }
                        - { join: c.phones, alias: phone, conditionType: WITH, condition: 'phone.primary = true' }
                        - { join: address.country, alias: country }
                        - { join: address.region, alias: region }
                        - { join: c.owner, alias: o }
            hints:
                - HINT_TRANSLATABLE
        inline_editing:
            enable: true
        columns:
            fullName:
                label:      oro.contact.gridview.fullname.label
                renderable: true
            firstName:
                label:         oro.contact.first_name.label
                renderable: false
            lastName:
                label:         oro.contact.last_name.label
                renderable: false
            birthday:
                label:         oro.contact.birthday.label
                frontend_type: date
                renderable: false
            gender:
                label:         oro.contact.gender.label
                frontend_type: select
                choices: "@oro_user.gender_provider->getChoices"
                renderable: false
            email:
                label:         oro.contact.email.label
                inline_editing:
                    enable: true
                    validation_rules:
                        Email: true
                    save_api_accessor:
                        class: orocontact/js/datagrid/inline-editing/save-api-accessor
                        route_create_entity:
                            name: oro_api_post_contact_email
                            http_method: POST
                        route_delete_entity:
                            name: oro_api_delete_contact_email
                            http_method: DELETE
                        default_route_parameters:
                            className: Oro_Bundle_ContactBundle_Entity_ContactEmail
                        route_parameters_rename_map:
                            emailId: id
            phone:
                label:         oro.contact.contactphone.phone.label
                frontend_type: phone
                inline_editing:
                    enable: true
                    editor:
                        view: oroform/js/app/views/editor/text-editor-view
                    save_api_accessor:
                        class: orocontact/js/datagrid/inline-editing/save-api-accessor
                        route_create_entity:
                            name: oro_api_post_contact_phone
                            http_method: POST
                        route_delete_entity:
                            name: oro_api_delete_contact_phone
                            http_method: DELETE
                        default_route_parameters:
                            className: Oro_Bundle_ContactBundle_Entity_ContactPhone
                        route_parameters_rename_map:
                            phoneId: id
            countryName:
                label:         oro.contact.contactaddress.country.label
                renderable:    false
            regionLabel:
                label:         oro.contact.contactaddress.region.label
                renderable:    false
            addressPostalCode:
                label:         oro.contact.contactaddress.postal_code.label
                renderable:    false
            addressCity:
                label:         oro.contact.contactaddress.city.label
                renderable:    false
            addressStreet:
                label:         oro.contact.contactaddress.street.label
                renderable:    false
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
                renderable:    false
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
                renderable:    false
            user:
                renderable: false
            country_of_birth:
                renderable: false
            further_activities:
                renderable: false
            bible_study:
                renderable: false
            homes:
                renderable: false
            sunday_worship:
                renderable: false
            christian_courses:
                renderable: false
            mhl:
                renderable: false
            baptised_by_us:
                renderable: false
            believed_thr_us:
                renderable: false
            christian:
                renderable: false
            marital_status:
                renderable: false
            month_of_commencement:
                renderable: false
            out_of_town:
                renderable: false
            year_of_birth:
                renderable: false
            degrees:
                renderable: false
            int_student:
                label: 'Int'
                renderable: false
            institutions:
                label: 'Institution'
                renderable: false
            contact_status:
                renderable: false
            level_of_study:
                renderable: false
            ethnicity:
                renderable: false
            church_kid:
                renderable: false
            contact_source:
                label:  'Source'
                renderable: false
            semester_contacted:
                label:  'Semester'
                renderable: true
            auto_allocate:
                renderable: false
            closed_date:
                 frontend_type: date
                 renderable: false
            last_review:
                frontend_type: date
                renderable: false
            closed_reason:
                renderable: false
            status:
                label:      oro.contact.status.label
                renderable: true
            review_request:
                renderable: false
            ownerName:
                inline_editing:
                    enable: true
                    editor:
                        view: oroform/js/app/views/editor/related-id-relation-editor-view
                        view_options:
                            value_field_name: owner
                    autocomplete_api_accessor:
                        class: orouser/js/tools/acl-users-search-api-accessor
                        permission_check_entity_name: Oro_Bundle_ContactBundle_Entity_Contact
                label:      oro.contact.owner.label
                renderable: false
                frontend_type: relation
        properties:
            id: ~
            emailId: ~
            phoneId: ~
            view_link:
                type:       url
                route:      oro_contact_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_contact_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_contact
                params:     [ id ]
        sorters:
            columns:
                fullName:
                    data_name: fullName
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
                birthday:
                    data_name: c.birthday
                gender:
                    data_name: c.gender
                email:
                    data_name: email.email
                phone:
                    data_name: phone.phone
                countryName:
                    data_name: country.name
                regionLabel:
                    data_name: regionLabel
                addressPostalCode:
                    data_name: address.postalCode
                addressCity:
                    data_name: address.city
                addressStreet:
                    data_name: address.street
                createdAt:
                    data_name: c.createdAt
                updatedAt:
                    data_name: c.updatedAt
                ownerName:
                    data_name: ownerName
            default:
                createdAt:  %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
               # firstName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName
                birthday:
                    type: date
                    data_name: c.birthday
                    enabled: false
                gender:
                    type: choice
                    data_name: c.gender
                    options:
                        field_options:
                            choices: "@oro_user.gender_provider->getChoices"
                    enabled: false
                email:
                    type: string
                    data_name: email.email
                    enabled: false
                phone:
                    type: string
                    data_name: phone.phone
                    enabled: false
                countryName:
                    type: choice
                    data_name: address.country
                    enabled: false
                    options:
                        field_options:
                            choices: "@oro_address.provider.country->getCountriesNames"
                            translatable_options: false
                regionLabel:
                    type: string
                    data_name: regionLabel
                    enabled: false
                addressPostalCode:
                    type: string
                    data_name: addressPostalCode
                    enabled: false
                addressCity:
                    type: string
                    data_name: addressCity
                    enabled: false
                addressStreet:
                    type: string
                    data_name: addressStreet
                    enabled: false
                createdAt:
                    type:      datetime
                    data_name: c.createdAt
                    enabled: false
                updatedAt:
                    type:      datetime
                    data_name: c.updatedAt
                    enabled: false
                owner:
                    enabled: false
                    type: choice-tree
                    label: oro.user.owner.label
                    data_name: c.owner
                    autocomplete_alias: users
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'
                duplicate:
                    type: duplicate
                    data_name: email.email
                    visible: false
                semester_contacted:
                    type: string
                    data_name: semester_contacted
                    enabled: true
                status:
                    type: string
                    data_name: status
                    enabled: true
        actions:
            view:
                type: navigate
                acl_resource: oro_contact_view
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: oro_contact_update
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                type: delete
                acl_resource: oro_contact_delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        mass_actions:
            merge:
                type: merge
                entity_name: %oro_contact.entity.class%
                data_identifier: c.id
        options:
            entityHint: contacts
            export: true
            entity_pagination: true
       # views_list: '@oro_contact.contacts_view_list'

    all-contacts-grid:
        extends: campus-contacts-grid
        columns:
            ownerName:
                renderable: true

    followup-contacts-grid:
#        source:
#            bind_parameters:
#                - step
        extends: campus-contacts-grid
        columns:
            email:
                renderable: true
            ownerName:
                renderable: true
        filters:
            default:
                status:
                    value: 'Follow-up'
                owner:
                    value: CONCAT_WS('',@oro_security.token_accessor->getUserId)
            columns:
                status:
                    type: string
                    data_name: status
                    enabled: true
                owner:
                    enabled: true
                    type: choice-tree
                    label: oro.user.owner.label
                    data_name: c.owner
                    autocomplete_alias: users
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'

    contacted-contacts-grid:
        extends: followup-contacts-grid
        filters:
            default:
                status:
                    value: 'Contacted'

    stable-contacts-grid:
        extends: followup-contacts-grid
        filters:
            default:
                status:
                    value: 'Stable'

    assigned-contacts-grid:
        extends: followup-contacts-grid
        filters:
            default:
                status:
                    value: 'Assigned'

    closed-contacts-grid:
        extends: followup-contacts-grid
        filters:
            default:
                status:
                    value: 'Closed'

    transfer-contacts-grid:
        extends: followup-contacts-grid
        filters:
            default:
                status:
                    value: 'Transfer'

    unassigned-contacts-grid:
        extends: campus-contacts-grid
        columns:
            email:
                renderable: true
            ownerName:
                renderable: true
        filters:
            default:
                status:
                    value: 'Unassigned'
            columns:
                status:
                    type: string
                    data_name: status
                    enabled: true
        mass_actions:
            autoallocate:
                type: autoallocate
                entity_name: %oro_contact.entity.class%
                data_identifier: c.id
                icon: wrench
                label: oro.contact.gridview.autoallocate.label

    review-contacts-grid:
        extends: campus-contacts-grid
        acl_resource: oro_contact_view
        columns:
            timesContacted:
                renderable: true
            lastContactedDate:
                renderable: true
            daysSinceLastContact:
                renderable: true
            email:
                renderable: false
            ownerName:
                renderable: false
        filters:
            default:
                review_request:
                    value: '1'
                owner:
                    value: CONCAT_WS('',@oro_security.token_accessor->getUserId)
            columns:
                owner:
                    enabled: true
                    type: choice-tree
                    label: oro.user.owner.label
                    data_name: c.owner
                    autocomplete_alias: users
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'
                review_request:
                    type: boolean
                    data_name: review_request
                    enabled: true
                contact_source:
                    type: enum
                    data_name: contact_source
                    enum_code: contact_source_source
                    enabled: true
        mass_actions:
            resetreviewrequest:
                type: resetreviewrequest
                entity_name: %oro_contact.entity.class%
                data_identifier: c.id
                icon: minus
                label: oro.contact.resetreviewrequest.label