workflows:
    contact_feedback:
        entity: Oro\Bundle\ContactBundle\Entity\Contact
        is_system: true
        entity_attribute: contact
        force_autostart: false
        steps_display_ordered: false
        defaults:
            active: true
        priority: 20
        applications: [ 'default' ]
        start_step: no_feedback
        steps:
            no_feedback:
                order: 10
                allowed_transitions:
                    - add_feedback
            feedback_completed:
                is_final: true
                order: 20
                allowed_transitions:
                    - edit_feedback
        attributes:
            bible_study:
                type: boolean
                property_path: contact.bible_study
            mhl:
                type: boolean
                property_path: contact.mhl
            christian_courses:
                type: boolean
                property_path: contact.christian_courses
            sunday_worship:
                type: boolean
                property_path: contact.sunday_worship
            homes:
                type: boolean
                property_path: contact.homes
            further_activities:
                type: boolean
                property_path: contact.further_activities
        transitions:
            add_feedback:
                step_to:  feedback_completed
                is_unavailable_hidden: true
                frontend_options:
                    icon: comment
                    class: 'btn-primary'
                transition_definition: add_def
                form_options:
                    attribute_fields:
                        bible_study:
                            form_type: checkbox
                            options:
                                required: true
                        mhl:
                            form_type: checkbox
                            options:
                                required: true
                        christian_courses:
                            form_type: checkbox
                            options:
                                required: true
                        sunday_worship:
                            form_type: checkbox
                            options:
                                required: true
                        homes:
                            form_type: checkbox
                            options:
                                required: true
                        further_activities:
                            form_type: checkbox
                            options:
                                required: true
                    attribute_default_values:
                        bible_study: false
                        mhl: false
                        christian_courses: false
                        sunday_worship: false
                        homes: false
                        further_activities: false
            edit_feedback:
                step_to:  feedback_completed
                is_unavailable_hidden: true
                frontend_options:
                    icon: comments
                    class: 'btn-success'
                transition_definition: edit_def
                form_options:
                    attribute_fields:
                        bible_study:
                            form_type: checkbox
                            options:
                                required: true
                        mhl:
                            form_type: checkbox
                            options:
                                required: true
                        christian_courses:
                            form_type: checkbox
                            options:
                                required: true
                        sunday_worship:
                            form_type: checkbox
                            options:
                                required: true
                        homes:
                            form_type: checkbox
                            options:
                                required: true
                        further_activities:
                            form_type: checkbox
                            options:
                                required: true
                    attribute_default_values:
                        bible_study: $contact.bible_study
                        mhl: $contact.mhl
                        christian_courses: $contact.christian_courses
                        sunday_worship: $contact.sunday_worship
                        homes: $contact.homes
                        further_activities: $contact.further_activities
        transition_definitions:
             add_def: ~
             edit_def: ~

    contact_followup:
        entity: Oro\Bundle\ContactBundle\Entity\Contact
        is_system: true
        entity_attribute: contact
        force_autostart: true
        steps_display_ordered: false
        defaults:
            active: true
        priority: 10
        applications: [ 'default' ]
        start_step: unassigned
        steps:
            unassigned:
                order: 10
                allowed_transitions:
                    - assign
            assigned:
                order: 20
                allowed_transitions:
                    - contacted
            contacted:
                order: 30
                allowed_transitions:
                    - followup
                    - drop
            followup:
                order: 35
                allowed_transitions:
                    - stable
                    - drop
                    - rollover
                    - transfer
            stable:
                order: 40
                allowed_transitions:
                    - followup
                    - rollover
                    - transfer
            closed:
                order: 50
                allowed_transitions:
                    - reopen
            transfer:
                is_final: true
                order: 60
        attributes:
            church_kid:
                type:       bool
            # call log attributes
            call_subject:
                type:       string
            call_comments:
                type:       string
            contact:
                type:       entity
                options:
                    class: Oro\Bundle\ContactBundle\Entity\Contact
            call_date:
                type:       object
                options:
                    class: Oro\Bundle\FormBundle\Form\Type\OroDateTimeType
            call_direction:
                type:       string
            owner:
                type: entity
                options:
                    class: Oro\Bundle\UserBundle\Entity\User
            auto_allocate:
                type: boolean
                property_path: contact.auto_allocate
        transitions:
            assign:
                step_to:  assigned
                is_hidden: true
                frontend_options:
                    icon: 'fa-sign-in'
                    class: 'btn-success'
                transition_definition: assign_def
 #               form_options:
 #                   attribute_fields:
 #                       owner:
 #                           form_type: oro_user_select
 ##                           options:
  #                              required: false
  #                      auto_allocate:
  #                          form_type: checkbox
  #                          options:
  #                              required: true
  #                  attribute_default_values:
  #                      owner: $contact.owner
  #                      auto_allocate: false
            rollover:
                is_hidden: true
                step_to: assigned
                frontend_options:
                    icon: 'fa-thumbs-up'
                    class: 'btn-warning'
                transition_definition: rollover_def
            reopen:
                step_to: followup
                frontend_options:
                    icon: 'fa-sign-in'
                    class: 'btn-success'
                transition_definition: reopen_def
            contacted:
                is_hidden: true
                step_to: contacted
                transition_definition: contacted_def
            followup:
                is_hidden: true
                step_to: followup
                transition_definition: followup_def
            stable:
                is_hidden: true
                step_to: stable
                transition_definition: stable_def
            drop:
                step_to: closed
                frontend_options:
                    icon: 'fa-times'
                    class: 'btn-danger'
                transition_definition: close_def
            transfer:
                step_to: transfer
                frontend_options:
                    icon: 'fa-times'
                    class: 'btn-danger'
                transition_definition: transfer_def
        transition_definitions:
             assign_def:
#                conditions:
                # $owner is empty AND $auto_allocate is true OR $owner have value AND $auto_allocate is false
#                  '@or':
#                      - '@and':
#                          message: You must select either Owner to or Auto allocate. But you cannot select both.
#                          parameters:
#                            - '@not_empty': [$owner]
#                            - '@equal': [$auto_allocate,false]
#                      - '@and':
#                          parameters:
#                            - '@empty': [$owner]
#                            - '@equal': [$auto_allocate,true]
                actions:
                  - '@auto_allocate_workflow':
                      owner: $owner
                      entity_class: $.entity
                      auto_allocate: $auto_allocate
             reopen_def: ~
             followup_def: ~
             stable_def: ~
             close_def: ~
             contacted_def:
                # Not contacted yet.
                preconditions:
                    @equal: [$request.church_kid, false]
             rollover_def: ~
             transfer_def: ~