services:
    campus_contact.validator.contactinfocheck:
        class: 'CampusCRM\CampusContactBundle\Validator\Constraints\ContactInfoCheckValidator'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: campus_contact.validator.contactinfocheck }

    campus_contact.subscriber.contact_listener:
        class: 'CampusCRM\CampusContactBundle\EventListener\ContactListener'
        arguments:
            - "@security.token_storage"
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate  }
            - { name: doctrine.event_listener, event: loadClassMetadata }

    oro_contact.mass_action.handler.autoallocate:
        class: CampusCRM\CampusContactBundle\Datagrid\Extension\MassAction\AutoAllocateActionHandler
        arguments:
            - '@oro_workflow.manager'
            - '@service_container'
            - '@translator'
            - '@oro_entity_merge.doctrine_helper'

    oro_contact.auto_allocate_workflow:
        class: CampusCRM\CampusContactBundle\Model\Action\AutoAllocateOwnerWorkflow
        arguments:
            - "@oro_action.expression.context_accessor"
            - "@service_container"
        tags:
            - { name: oro_action.action, alias: auto_allocate_workflow }

    oro_contact.auto_owner_allocator:
        class: CampusCRM\CampusContactBundle\Manager\AutoOwnerAllocator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    oro_contact.contact_grid_view_list:
        class: 'CampusCRM\CampusContactBundle\Datagrid\ContactExtraViewList'
        arguments:
            - '@translator'
        calls:
            - [setToken, ['@security.token_storage']]

    oro_contact.form_type_extension:
        class: 'CampusCRM\CampusContactBundle\Form\Extension\CampusContactTypeExtension'
        arguments:
            - '@service_container'
        tags:
            - { name: form.type_extension, alias: oro_contact }

    campus_contact.workflow.manager:
        class: 'CampusCRM\CampusContactBundle\Manager\WorkflowManager'
        arguments:
            - '@oro_workflow.registry'
            - '@oro_entity.doctrine_helper'
            - '@oro_workflow.changes.event.dispatcher'
            - '@oro_workflow.entity_connector'
            - '@oro_workflow.started_workflows.bag'
            - '@service_container'