Oro\Bundle\ContactBundle\Entity\Contact:
    constraints:
        - CampusCRM\CampusContactBundle\Validator\Constraints\ContactInfoCheck: { groups: [contact_info_check] }
    properties:
        firstName:
            - NotBlank:
                groups: [contact_info_check]
        lastName:
            - NotBlank:
                groups: [contact_info_check]
        gender:
            - NotBlank:
                groups: [contact_info_check]
        contact_source:
            - NotBlank:
                groups: [contact_info_check]
#        church_kid:
#            - NotBlank:
#                groups: [contact_info_check]