Oro\Bundle\UserBundle\Entity\User:
    properties:
        contact:
            - NotBlank: { groups: [user_contact_link] }
            - CampusCRM\CampusUserBundle\Validator\Constraints\UserContactLink: { groups: [user_contact_link] }