datagrids:
    related-events-grid:
        acl_resource: oro_eventname_view
        source:
            type: orm
            query:
                select:
                    - partial event.{ id, start, recurrence, cancelled }
                    - event.id
                    - COALESCE(calendar.name, CONCAT_WS(' ', owner.firstName, owner.lastName)) AS name
                    - event.title
                    - event.start
                    - event.end
                    - COALESCE(status.id, 'Oro\Bundle\CalendarBundle\Entity\Attendee::STATUS_NONE') as invitationStatus
                    - parent.id as parentId
                    - owner.id as ownerId
                    - relatedAttendeeUser.id as relatedAttendeeUserId
                    - (CASE WHEN (event.recurrence IS NOT NULL OR parent.recurrence IS NOT NULL) THEN true ELSE false END) as is_recurrent
                    - recurringEvent
                    - recurringEventRecurrence
                    - parent
                    - parentRecurringEvent
                    - parentRecurringEventRecurrence
                from:
                    - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
                join:
                    left:
                        - { join: event.parent, alias: parent }
                        - { join: event.oro_eventname, alias: eventname }
                        - { join: event.relatedAttendee, alias: ra }
                        - { join: ra.status, alias: status }
                        - { join: ra.user, alias: relatedAttendeeUser }
                        - { join: event.recurrence, alias: recurrence }
                        - { join: event.recurringEvent, alias: recurringEvent }
                        - { join: recurringEvent.recurrence, alias: recurringEventRecurrence }
                        - { join: parent.recurringEvent, alias: parentRecurringEvent }
                        - { join: parentRecurringEvent.recurrence, alias: parentRecurringEventRecurrence }
                    inner:
                        - { join: event.calendar, alias: calendar }
                        - { join: calendar.owner, alias: owner }
                        -
                            join: %oro_calendar.calendar_property.entity.class%
                            alias: connection
                            conditionType: WITH
                            condition: "connection.calendarAlias = 'user' AND connection.calendar = calendar.id AND connection.visible = true"
                        - { join: connection.targetCalendar, alias: targetCalendar }
                where:
                    and:
                        - targetCalendar.owner = @oro_security.security_facade->getLoggedUserId
                        - event.cancelled = false
                        - eventname.id = :viewEventnameId
                groupBy: >
                    event.id,
                    calendar.name,
                    owner.firstName,
                    owner.lastName,
                    parent.id,
                    owner.id,
                    status.id,
                    relatedAttendeeUser.id,
                    recurrence.id,
                    recurringEvent.id,
                    recurringEventRecurrence.id,
                    parentRecurringEvent.id,
                    parentRecurringEventRecurrence.id
            bind_parameters:
                - viewEventnameId
        columns:
            title:
                label: oro.calendar.calendarevent.title.label
            name:
                label: oro.calendar.calendarevent.calendar.label
            start:
                label: oro.calendar.calendarevent.start.label
                frontend_type: datetime
            end:
                label: oro.calendar.calendarevent.end.label
                frontend_type: datetime
            is_recurrent:
                label: oro.calendar.calendarevent.recurrence.alias.recurrent
                frontend_type: boolean
            recurrence:
                label: oro.calendar.calendarevent.recurrence.label
                type: twig
                template: OroCalendarBundle:CalendarEvent:Datagrid/Property/recurrence.html.twig
                frontend_type: html
            invitationStatus:
                label: oro.calendar.calendarevent.invitation_status.label
                type: twig
                template: OroCalendarBundle:CalendarEvent:Datagrid/Property/status.html.twig
                frontend_type: html
        sorters:
            columns:
                title:
                    data_name: event.title
                name:
                    data_name: name
                start:
                    data_name: event.start
                end:
                    data_name: event.end
                invitationStatus:
                    data_name: invitationStatus
            default:
                start: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: event.title
                name:
                    type: string
                    data_name: name
                start:
                    type: datetime
                    data_name: event.start
                end:
                    type: datetime
                    data_name: event.end
                is_recurrent:
                    type: boolean
                    data_name: is_recurrent
                invitationStatus:
                    type: enum
                    enum_code: ce_attendee_status
                    data_name: invitationStatus
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_calendar_event_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_calendar_event_update
                params:     [ id ]
            delete_link:
                type:     callback
                callable: "@oro_calendar.datagrid.helper.calendar_event_grid->getDeleteLinkProperty"
                route:    oro_calendar_event_delete
            accept_link:
                type:       url
                route:      oro_calendar_event_accepted
                params:     [ id ]
            tentative_link:
                type:       url
                route:      oro_calendar_event_tentative
                params:     [ id ]
            decline_link:
                type:       url
                route:      oro_calendar_event_declined
                params:     [ id ]
        actions:
            accept:
                type:         ajax
                label:        oro.calendar.calendarevent.action.status.accepted.label
                link:         accept_link
                icon:         check
                acl_resource: oro_calendar_event_view
            tentative:
                type:         ajax
                label:        oro.calendar.calendarevent.action.status.tentative.label
                link:         tentative_link
                icon:         question
                acl_resource: oro_calendar_event_view
            decline:
                type:         ajax
                label:        oro.calendar.calendarevent.action.status.declined.label
                link:         decline_link
                icon:         close
                acl_resource: oro_calendar_event_view
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye
                acl_resource: oro_calendar_event_view
                rowAction:    true
            update:
                type:          navigate
                acl_resource:  oro_calendar_event_create
                label:         oro.grid.action.update
                icon:          pencil-square-o
                link:          update_link
        options:
            entityHint: calendar event
            entity_pagination: true

    eventnames-grid:
        extended_entity_name: %event_name.entity.eventname.class%
        inline_editing:
            enable: true
        acl_resource: oro_eventname_view
        source:
            type: orm
            query:
                select:
                    - a.id
                    - a.name
                    - a.createdAt
                    - a.updatedAt
                    - eventnameOwner.id as owner
                from:
                    - { table: %event_name.entity.eventname.class%, alias: a }
                join:
                    left:
                         - { join: a.owner, alias: eventnameOwner }
        properties:
            id: ~
            owner: ~
            view_link:
                type:       url
                route:      oro_eventname_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_eventname_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_eventname
                params:     [ id ]
        columns:
            name:
                label:         oro.eventname.name.label
            ownerName:
                label:         oro.eventname.owner.label
                frontend_type: relation
                inline_editing:
                    enable: true
                    editor:
                        view_options:
                            value_field_name: owner
                    autocomplete_api_accessor:
                        class: orouser/js/tools/acl-users-search-api-accessor
                        permission_check_entity_name: Oro_Bundle_AccountBundle_Entity_Account
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        fields_acl:
            columns:
                name:
                    data_name: a.name
                ownerName:
                    data_name: a.owner
                createdAt:
                    data_name: a.createdAt
                updatedAt:
                    data_name: a.updatedAt
        sorters:
            columns:
                name:
                    data_name: a.name
                ownerName:
                    data_name: ownerName
                createdAt:
                    data_name: a.createdAt
                updatedAt:
                    data_name: a.updatedAt
        filters:
            columns:
                name:
                    type:      string
                    data_name: a.name
                owner:
                    type: choice-tree
                    label: oro.user.owner.label
                    data_name: a.owner
                    autocomplete_alias: users
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'
                businessUnitId:
                    label: oro.business_unit.label
                    type: choice-business-unit
                    data_name: a.owner
                    className: 'Oro\Bundle\OrganizationBundle\Entity\BusinessUnit'
                createdAt:
                    type:      datetime
                    data_name: a.createdAt
                updatedAt:
                    type:      datetime
                    data_name: a.updatedAt
                duplicate:
                    type: duplicate
                    data_name: a.name
                    visible: false
        actions:
            view:
                type:          navigate
                acl_resource:  oro_eventname_view
                label:         oro.grid.action.view
                icon:          eye
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_eventname_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_eventname_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
                defaultMessages:
                    confirm_content: oro.ui.delete_confirm_cascade
                    confirm_content_params:
                        entity_label: '@translator->trans(oro.account.entity_label)'

        mass_actions:
            merge:
                type: merge
                entity_name: %event_name.entity.eventname.class%
                data_identifier: a.id
        options:
            entityHint: eventname
            export: true
            entity_pagination: true
        views_list: '@event_name.eventnames_view_list'
