CampusCRM\EventNameBundle\Entity\EventName:
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max:        255
            - CampusCRM\EventNameBundle\Validator\Constraints\UniqueName: { groups: [unique_name] }
